name: RE4ModCheckerCI/CD

"on":
  push:
    branches: [main]

jobs:
  unit-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          os: ${{ matrix.os }}
          python-version: ${{ matrix.python-version }}
      - name: Run unit-tests
        run: make unit-tests

  linting:
    needs: unit-tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          os: ${{ matrix.os }}
          python-version: ${{ matrix.python-version }}
      - name: Run linting
        run: make linting