name: Tag-Release

"on":
  push:
    branches: ['main']

jobs:
  tag-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          os: ${{ matrix.os }}
          python-version: ${{ matrix.python-version }}
      - name: Run tag-release
        run: |
            oldVer=$(poetry version --short)
            ver=$(make bump-version)
            poetryVersion=$(poetry version --short)
            if [ $oldVer == $poetryVersion ]; then
                echo "Not a release version, nothing to do..."
            else
                git add pyproject.toml
                newVersion="v$poetryVersion"
                git commit -m "Bumping Release Version to $newVersion"
                git tag -a $newVersion -m "Version $newVersion"
                git push
                git push origin $newVersion
            fi
        env:
            commit_msg: ${{ github.event.head_commit.message }}
            github_token: ${{ secrets.GH_TOKEN }}
